project_name: errors

builds:
  - id: "linux"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X "github.com/tfadeyi/{{ .ProjectName }}/internal/version.Platform=linux/unknown" -X "github.com/tfadeyi/{{ .ProjectName }}/internal/version.Version={{ .Version }}" -X "github.com/tfadeyi/{{ .ProjectName }}/internal/version.Commit={{ .Commit }}" -X "github.com/tfadeyi/{{ .ProjectName }}/internal/version.Date={{ .Date }}"'
    binary: "fyictl"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
  - id: "darwin"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X "github.com/tfadeyi/{{ .ProjectName }}/internal/version.Platform=darwin/unknown" -X "github.com/tfadeyi/{{ .ProjectName }}/internal/version.Version={{ .Version }}" -X "github.com/tfadeyi/{{ .ProjectName }}/internal/version.Commit={{ .Commit }}" -X "github.com/tfadeyi/{{ .ProjectName }}/internal/version.Date={{ .Date }}"'
    binary: "fyictl"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: linux
    format: tar.gz
    name_template: "fyictl-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    builds:
      - "linux"
  - id: darwin
    format: tar.gz
    name_template: "fyictl-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    builds:
      - "darwin"

kos:
  - working_dir: .
    id: "linux"
    build: "linux"
    base_image: gcr.io/distroless/base:nonroot
    # labels are going to be supported in goreleaser 1.16.3, waiting for the release
    labels:
      org.opencontainers.image.source: https://github.com/tfadeyi/errors
      org.opencontainers.image.description: "fyictl is a CLI utility for generating an application error manifest"
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.title: "fyictl"
      org.opencontainers.image.vendor: ""
      org.opencontainers.image.authors: "Oluwole Fadeyi"

    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
    tags:
      - latest
      - '{{.Tag}}'
    sbom: cyclonedx
    bare: true
    base_import_paths: true

checksum:
  name_template: "fyictl-SHA256SUMS"
  algorithm: sha256
release:
  draft: true
changelog:
  use: github-native
  skip: false

signs:
  - cmd: cosign
    args:
      - "sign-blob"
      - "${artifact}"
      - "--output-signature=${signature}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
