schema = 3

[mod]
  [mod."github.com/tfadeyi/aloe-bindings/src/go"]
    version = "v0.0.0-20230518203317-6ddf769067e4"
    hash = "sha256-5wjo5fyBusIrIrpNFZyI6AQP2wyAV+//FOwGvxgHDjo="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
