package app

import (
	"bytes"
	"io"
	"os"

	"github.com/juju/errors"
	"github.com/spf13/cobra"
	commonoptions "github.com/tfadeyi/errors/cmd/app/options/common"
	manifestoptions "github.com/tfadeyi/errors/cmd/app/options/manifest"
	genoptions "github.com/tfadeyi/errors/cmd/app/options/manifest/generate"
	"github.com/tfadeyi/errors/internal/generate/manifest"
	"github.com/tfadeyi/errors/internal/logging"
	"github.com/tfadeyi/errors/internal/parser"
	api "github.com/tfadeyi/errors/pkg/api/v0.1.0"
)

func manifestCmd(common *commonoptions.Options) *cobra.Command {
	opts := manifestoptions.New(common)
	cmd := &cobra.Command{
		Use:   "manifest",
		Short: "manifest command",
		Long:  ``,
		PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
			logger := logging.LoggerFromContext(cmd.Context())
			logger = logger.WithName("manifest")

			if opts.LogLevel != "" {
				logger = logger.SetLevel(opts.LogLevel)
			}
			cmd.SetContext(logging.ContextWithLogger(cmd.Context(), logger))
			return nil
		},
	}
	opts = opts.Prepare(cmd)
	cmd.AddCommand(manifestGenerateCmd(opts))
	cmd.AddCommand(manifestValidateCmd(opts))
	return cmd
}

func manifestGenerateCmd(manifestOpts *manifestoptions.Options) *cobra.Command {
	opts := genoptions.New(manifestOpts)
	var inputReader io.Reader
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Generates the targeted application error manifest from a given source code",
		Long:  ``,
		PreRunE: func(cmd *cobra.Command, args []string) error {
			logger := logging.LoggerFromContext(cmd.Context())
			logger = logger.WithName("create")

			if err := opts.Complete(); err != nil {
				return err
			}

			if opts.Source == "-" {
				inputReader = cmd.InOrStdin()
			} else if opts.Source != "" {
				buf, err := os.ReadFile(opts.Source)
				if err != nil {
					return err
				}
				inputReader = bytes.NewReader(buf)
			}

			cmd.SetContext(logging.ContextWithLogger(cmd.Context(), logger))
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			logger := logging.LoggerFromContext(cmd.Context())

			logger.Info("Generating application error manifest")

			logger.Info("Parsing source code for @fyi error definitions",
				"directories", opts.IncludedDirs,
				"output", opts.Output,
			)

			parserOptions := []parser.Option{
				parser.Include(opts.IncludedDirs...),
				parser.Recursive(true),
				parser.Logger(&logger),
				parser.Strict(opts.Strict),
			}

			// check language options
			switch opts.Language {
			default:
				parserOptions = append(parserOptions, parser.Go(cmd.Context()))
			}

			p := parser.New(
				parserOptions...,
			)

			var apps []*api.Manifest
			if inputReader != nil {
				man, err := p.ParseSource(cmd.Context(), inputReader)
				if err != nil {
					return errors.Annotate(err, "failed to parse the application(s) error manifests")
				}
				apps = append(apps, man)
			} else {
				manifests, err := p.ParseAllSources(cmd.Context())
				if err != nil {
					return errors.Annotate(err, "failed to parse the application(s) error manifests")
				}
				apps = manifests
			}

			logger.Info("Source code was successfully parsed ✅")

			generatorOptions := []manifest.Option{
				manifest.Logger(&logger),
				manifest.Output(opts.Output),
				manifest.Watermark(`# Code generated by fyictl: https://github.com/tfadeyi/errors.
# DO NOT EDIT.`),
				manifest.YAML(),
				manifest.Writer(cmd.OutOrStdout()),
			}

			gen := manifest.New(generatorOptions...)
			if err := gen.GenerateManifests(cmd.Context(), apps...); err != nil {
				return errors.Annotate(err, "failed to printout the application(s) error manifests")
			}

			logger.Info("Application error manifest were successfully generated!")

			return nil
		},
	}
	opts = opts.Prepare(cmd)
	return cmd
}

func manifestValidateCmd(manifestOptions *manifestoptions.Options) *cobra.Command {
	var inputReader io.Reader
	cmd := &cobra.Command{
		Use:   "validate",
		Short: "Validates a given application error manifest",
		Long:  ``,
		PreRunE: func(cmd *cobra.Command, args []string) error {
			logger := logging.LoggerFromContext(cmd.Context())
			logger = logger.WithName("validate")

			if err := manifestOptions.Complete(); err != nil {
				return err
			}

			if manifestOptions.Source == "-" {
				inputReader = cmd.InOrStdin()
			} else {
				buf, err := os.ReadFile(manifestOptions.Source)
				if err != nil {
					return err
				}
				inputReader = bytes.NewReader(buf)
			}

			cmd.SetContext(logging.ContextWithLogger(cmd.Context(), logger))
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			logger := logging.LoggerFromContext(cmd.Context())

			logger.Info("Validating application error manifest", "file", manifestOptions.Source)
			_, err := manifest.ValidateFromReader(inputReader)
			if err != nil {
				logger.Error(err, "Application error manifest contains errors")
				return nil
			}
			logger.Info("Application error manifest is valid")
			return nil
		},
	}
	manifestOptions = manifestOptions.Prepare(cmd)
	return cmd
}
